### ISSUE TITLE
Retina audit

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#102]
Let's clean some of the assets up for retina screens.

![screenshot 2015-03-26 10 33 08](https://cloud.githubusercontent.com/assets/3422584/6848565/5b05d156-d3a4-11e4-98b0-4b70ef032774.png)

**Comment by gib** [comment]
Completed with Rebrand. SVGs used almost exclusively. Will make sure images used in the company page update are hi res.
