### ISSUE TITLE
Add GitHub and Twitter icons to footer

### ISSUE THREAD

**Issue by samyount** [aptible/www.aptible.com#105]
Let's put them fairly big in the footer like https://www.engineyard.com/ does.

Twitter should link to https://twitter.com/aptible
GitHub Should link to https://github.com/aptible

Let me know if you need me to track down icons to use for either.

**Comment by gib** [comment]
<img width="843" alt="gh_twitter_footer" src="https://cloud.githubusercontent.com/assets/94830/10645448/01146306-77eb-11e5-9a48-cf2c71e688f4.png">
<img width="831" alt="gh_twitter" src="https://cloud.githubusercontent.com/assets/94830/10645479/28d7dfda-77eb-11e5-8450-ba263fe376f1.png">

@samyount @sandersonet :+1: / :-1:  ?

**Comment by samyount** [comment]
Looks good to me.  But maybe move it to the upper right of the footer?
