### ISSUE TITLE
Pricing plan CTAs overflow on medium screens

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#114]
![screenshot 2015-05-05 14 39 25](https://cloud.githubusercontent.com/assets/3422584/7481363/fc233aa6-f334-11e4-812d-33b0a4fbc7c1.png)

**Comment by samyount** [comment]
The price we pay for vanity. @sandersonet I assume you have an elegant fix as opposed to my shorten the CTA solution.

Sam

**Comment by sandersonet** [comment]
The only other option is to let the text wrap and expand the height of the button and since the breakpoint that causes this is only 1200px in width, we may just want to reduce the length of the text

**Comment by chasballew** [comment]
Fixed by aptible-pages 2bc411
