### ISSUE TITLE
Plans should collapse gracefully

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#117]
On medium screens (991px wide down to 786, I believe), the pricing divs should just collapse if we can't fit them on one row. 

![screenshot 2015-06-04 12 27 06](https://cloud.githubusercontent.com/assets/3422584/7989147/98b4d8ce-0ab5-11e5-8453-408932e7bd35.png)

**Comment by gib** [comment]
New pricing calc handles this via https://github.com/aptible/www.aptible.com/pull/125
