### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by gib** [aptible/www.aptible.com#127]
- [ ] Fixed left column Nav (see https://slack.com/pricing FAQ section)
- [ ] Accordion Q/A (see https://slack.com/pricing FAQ section)
- [ ] Add a link to the FAQ in the footer under Support
- [ ] Populate content from FAQ page to pricing page  (Possible to make this repeatable functionality?  e.g. Do it again for compliance content

**Comment by gib** [comment]
Hey @samyount, the data sharing for FAQs that we discussed doesn't look possible with our current set up. I'll sync up with @sandersonet to see if he has any ideas, but I believe the only way to share the FAQs would be to put them in a yml file in the `www.aptible.com` repo... which kind of defeats our abstraction set up.

**Comment by samyount** [comment]
If we did use the yml setup could we have them populate the FAQ page and
other pages?  Though if it's a ton of work, it's not really worth doing.

On Fri, Jul 31, 2015 at 4:54 PM, Gib Reimschüssel <notifications@github.com>
wrote:

> Hey @samyount <https://github.com/samyount>, the data sharing for FAQs
> that we discussed doesn't look possible with our current set up. I'll sync
> up with @sandersonet <https://github.com/sandersonet> to see if he has
> any ideas, but I believe the only way to share the FAQs would be to put
> them in a yml file in the www.aptible.com repo... which kind of defeats
> our abstraction set up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aptible/www.aptible.com/issues/127#issuecomment-126830538>
> .
>



-- 
Sam Yount | Aptible
(650) 434-2028
Join us: we’re hiring <https://www.aptible.com/company/careers/>

**Comment by gib** [comment]
Closed with rebrand
