### ISSUE TITLE
Build new compliance page

### ISSUE THREAD

**Issue by samyount** [aptible/www.aptible.com#134]
Build new compliance page from the designs attached.

**Comment by samyount** [comment]
(Sketch File) [https://drive.google.com/open?id=0B9UtG5s_XaKqTmJVaEhjTFVCMlU]
(PDF)[https://drive.google.com/open?id=0B9UtG5s_XaKqdTNVS1RkclNTdHM]

**Comment by sandersonet** [comment]
I've updated the design to include more on-brand iconography:

[Sketch](https://drive.google.com/open?id=0Bxuaj2I3HLq-R3F0SzcxdDNWekU)
[PNG](https://drive.google.com/open?id=0Bxuaj2I3HLq-LW5uNkVLNGN1Tmc)

Also, assigning to @moeamaya

**Comment by samyount** [comment]
@moeamaya Do you mind building?

**Comment by moeamaya** [comment]
@samyount Will do!

**Comment by samyount** [comment]
Compliance page notes:
```1. Looks great
2. Convert the callout boxes (“sample risk assessment” + “training”) into customer references. Portrait of a customer and a quote. We can switch it out later or add links to collateral/webinars.
3. Move the social proof to the top and replicate on the home page.
4. Move incident response to be consistent with the other model components
5. Convert the bottom panel (“security program”) into something that demonstrates how the components work together. Consider using a version of the compliance model diagram.

**Comment by gib** [comment]
Closed via https://github.com/aptible/www.aptible.com/pull/145
