### ISSUE TITLE
Existing terminal styles gone

### ISSUE THREAD

**Issue by sandersonet** [aptible/www.aptible.com#142]
cc @gib or @moeamaya 

![screenshot 2015-08-27 09 10 37](https://cloud.githubusercontent.com/assets/884151/9521232/9f8f9116-4c9b-11e5-8d4b-90ed5e906f94.png)

**Comment by chasballew** [comment]
![](http://i.imgur.com/QKZ9xij.gif)

**Comment by moeamaya** [comment]
Damnit, I thought I went through every page. I'll get on it

**Comment by gib** [comment]
Happy to take this too, @moeamaya. Let me know.

**Comment by moeamaya** [comment]
@gib You're probably faster. Thanks for picking up my slack

https://github.com/aptible/www.aptible.com/commit/44fc85d460cf867ec5ccadb1554be366c0a3378e#diff-7159103469d3cdb01c593c8f00f0d32eL169

Deleted lines from L169 - L214 (may need to nest under homepage scss ie ".home .console")

**Comment by gib** [comment]
:+1: no problem!
