### ISSUE TITLE
/compliance - header SVGs have hidden components at certain breakpoints

### ISSUE THREAD

**Issue by gib** [aptible/www.aptible.com#149]
Looks like a side effect of the partials (https://github.com/aptible/www.aptible.com/pull/147).

<img width="957" alt="screen shot 2015-09-02 at 2 31 59 pm" src="https://cloud.githubusercontent.com/assets/94830/9643829/52ef7638-5181-11e5-8054-268c5bf58a0a.png">

@moeamaya - Looks like the styles used to hide the SVG in the sections below is cascading to the header.

**Comment by moeamaya** [comment]
What pixel dimension are you at? It's strange, if you drag the browser the svg's sometimes fail, but if you refresh the page at the same dimension, they are fine. Chrome bug or something in my code?

**Comment by moeamaya** [comment]
Oh damn it's the animation code. My bad I'll push a quick fix for that

**Comment by gib** [comment]
No worries. Looks like it could be related to the other uses of the SVG partials lower down because the security ops SVG, which isn't re-used doesn't have a problem.
760-990 is the width range:
![compliance-svg-responsive](https://cloud.githubusercontent.com/assets/94830/9645025/91e436a8-5186-11e5-9f77-43c91e5edac1.gif)

**Comment by moeamaya** [comment]
Animation code clean up did not fix it. I have no idea what's going on (no class/id collisions, no styles on the elements or it's parents, no obvious js style changes):

![screen shot 2015-09-02 at 2 41 20 pm](https://cloud.githubusercontent.com/assets/1373293/9645502/d5cf09de-5180-11e5-9de8-2f3f999a1d20.png)

**Comment by gib** [comment]
I can take a look @moeamaya. Interesting to note, safari has the same issue, but only with `<circle>` elements ¯\\\_(°\_o)_/¯ 
I wonder if simplifying the SVG groups (removing some of the nested `<g>`s) could help... simplify the SVG DOM?

**Comment by moeamaya** [comment]
Thanks @gib. I'll try that out and report back.

**Comment by moeamaya** [comment]
@gib No go on the svg code cleanup. tagging @sandersonet see if he has an exp with this issue.

I also just turned the svg into an image <img src=""> and that seemed to work perfectly fine. If we can't figure out the embedded version, i'll swap them back out.

**Comment by gib** [comment]
Closed via https://github.com/aptible/www.aptible.com/pull/153... sort of. Going to try some SVG clean up too... later.
