### ISSUE TITLE
/compliance - Editing titles breaks header

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#152]
![](http://g.recordit.co/b4N6viUdSf.gif)

**Comment by chasballew** [comment]
It also breaks the text element styling :/

<img width="352" alt="screenshot 2015-09-03 15 42 45" src="https://cloud.githubusercontent.com/assets/3422584/9671762/76945b68-5252-11e5-9929-7a5e7e9ab363.png">

**Comment by moeamaya** [comment]
I thought this might be an issue. I was following the conventions of the other scss stylesheets, but it probably doesn't make sense to scope things to editable content.

@gib should we inject an uneditable body class (or use one of the other ones) instead or the title ones?

**Comment by gib** [comment]
Good call. I've got a branch that uses one of the other page classes for scoping.

**Comment by moeamaya** [comment]
👍Thanks you're always on top of things!

**Comment by gib** [comment]
Closed via https://github.com/aptible/www.aptible.com/pull/153
