### ISSUE TITLE
Lost background style on pricing calculator hover tip

### ISSUE THREAD

**Issue by fancyremarker** [aptible/www.aptible.com#154]
![pricing-hover](https://cloud.githubusercontent.com/assets/156030/9696848/f0a0453a-5346-11e5-9a8f-94474790831b.gif)

**Comment by fancyremarker** [comment]
Thanks @jdl031 for the catch.

**Comment by gib** [comment]
Thanks @fancyremarker. This issue appears to be specific to Chrome version 45.0.2454.85.

**Comment by fancyremarker** [comment]
@gib: Confirmed. Seeing it on my other laptop, which is 45.0.2454.85. Fixed after update.
