### ISSUE TITLE
Scrolling down the /technology page scrolls back up?

### ISSUE THREAD

**Issue by gib** [aptible/www.aptible.com#166]
I think it is the auto-play / auto-advance not pausing (or stopping) once the user scrolls the page on their own.

To reproduce:
- load the technology page
- start scrolling to #stack, then scroll again... 
scrolls back up to the intro

I reproduced this in Safari and Chrome. Trying again now, I can't reproduce it. I was testing locally and on www.aptible.com.

**Comment by gib** [comment]
Ok. Got it reversing again and got it into a weird state:

<img width="1188" alt="screen shot 2015-11-03 at 3 43 42 pm" src="https://cloud.githubusercontent.com/assets/94830/10924101/db143198-8241-11e5-8928-b21aab4ddfbe.png">

**Comment by moeamaya** [comment]
@gib meant to create an issue last week. Noticed this also, but looks like it's fixed in the most recent version of fullPage.js https://github.com/alvarotrigo/fullPage.js/issues/1600

Let me know if the weird state happens with the update, I don't think that should happen again.

**Comment by moeamaya** [comment]
Oh also the reverse scroll happens when you lightly scroll on a trackpad. If you scroll deliberately it will work like normal, but I don't personally scroll forcefully like that (I assume most people don't?).

**Comment by gib** [comment]
Nice. Thanks @moeamaya. I'll try the update!

**Comment by gib** [comment]
Got this fixed and closed with an update to the jquery plugin that does the full page scrolling (see https://github.com/aptible/www.aptible.com/issues/179)
