### ISSUE TITLE
Sidebar nav collides with footer

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#314]
![a](https://cloud.githubusercontent.com/assets/3422584/19454340/fb36aebe-9475-11e6-86ee-0ba615f8e0f3.gif)

**Comment by gib** [comment]
To reproduce: https://www.aptible.com/legal/security/ and adjust the width while scrolling

**Comment by sandersonet** [comment]
On smaller widths, the sidebar sits on top of content as well:

https://www.dropbox.com/s/z4gzpgw1kbhz9wu/Screenshot%202016-10-17%2014.30.32.png?dl=0
