### ISSUE TITLE
Mobile screen width is too wide

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#317]
From a user: 

> On mobile (iPhone 7 Chrome) there is a white strip on the right side of the website. Just fyi. I imagine the goal was to have the width be fixed to exactly screen width.

![a](https://cloud.githubusercontent.com/assets/3422584/19484907/8d84681a-9516-11e6-983f-29d3e2cd67e0.gif)

**Comment by gib** [comment]
This was caused by the hidden mobile menu extending past the viewport width.
