### ISSUE TITLE
sitemap.xml has typo and is missing a line

### ISSUE THREAD

**Issue by henryhund** [aptible/www.aptible.com#371]
Google flags incorrectly formatted sitemaps and penalizes search ranking. Google's algorithm is a bit of a blackbox so it is impossible to forecast the impact, but we should get this fixed. Google is highlighting the issue in webmaster tools.

The sitemap should begin with:
`<?xml version="1.0" encoding="UTF-8"?>`

And here's the typo:

`<urlset xlmns="http://www.sitemaps.org/schemas/sitemap/0.9">`

Should be `xmlns` not `xlmns`

Also, less important, but in an ideal world we'd kill the 404 page from the sitemap. And, we'd add `<lastmod>`, `<changefreq>`, and `<priority>` to each `<url>` listing.

**Comment by henryhund** [comment]
Here's more info on how the sitemap should be formatted, for reference:

https://www.sitemaps.org/protocol.html

**Comment by gib** [comment]
Going to table the `<url>` attributes for now
> add `<lastmod>`, `<changefreq>`, and `<priority>` to each `<url>` listing.

**Comment by henryhund** [comment]
Makes sense.

**Comment by henryhund** [comment]
Also, I noticed we're missing all blog posts in the sitemap...

**Comment by gib** [comment]
Just finished pairing on this with @fancyremarker. The current sitemap.xml is from a previous project. We'll have all the pages now, fix is on the way.
