### ISSUE TITLE
When scrolling on mobile white takes the place of the background img for a few seconds

### ISSUE THREAD

**Issue by henryhund** [aptible/www.aptible.com#373]
I'm using iPhone 6, latest version iOS, Chrome browser. User experience is bad. Background and content disappears as you are scrolling. Reemerges a few seconds later.

I believe it is related to this: http://stackoverflow.com/questions/32417663/white-area-on-fixed-background-when-scrolling-on-ios

Hopefully is a simple fix.

**Comment by gib** [comment]
Fixed this by not displaying the scaling SVG grid background images on smaller screens.

**Comment by henryhund** [comment]
Has this been deployed?
