### ISSUE TITLE
Resources overflow on mobile

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#616]
![e021ba56-871a-4b07-82ba-b67c5f6e3825](https://user-images.githubusercontent.com/3422584/46777027-14e19680-ccdc-11e8-9e1f-d78fa0653f36.png)

We have a high SEO ranking for “HIPAA BAA” and several other terms, but clicking through is hard to read.

**Comment by mjp** [comment]
Fixed by #617
