### ISSUE TITLE
Page speed enhancements

### ISSUE THREAD

**Issue by sandersonet** [aptible/www.aptible.com#75]
- [ ] Minify HTML, CSS, and JS
- [ ] Audit image optimizations
- [ ] Optimize Typekit?
- [ ] Configure compression

http://developers.google.com/speed/pagespeed/insights/?url=www.aptible.com&tab=mobile

**Comment by gib** [comment]
Rebrand and middleman turbolinks addresses some of these. Will address more in another issue to get the site AMP compliant
