### ISSUE TITLE
Divs don't resize properly on med screens

### ISSUE THREAD

**Issue by chasballew** [aptible/www.aptible.com#81]
![screenshot 2014-09-09 10 57 22](https://cloud.githubusercontent.com/assets/3422584/4206462/7867ecc4-384b-11e4-9eb9-55fb527c1468.png)

May be the same issue as #69?

**Comment by fancyremarker** [comment]
Reproducible at 300 x 400:

![image](https://cloud.githubusercontent.com/assets/156030/10145119/412aa198-65ef-11e5-9d4a-f013b5ce023e.png)

**Comment by wcpines** [comment]
For me it was 848x625 with no UA/Dev specified: 

http://snag.gy/9lb5L.jpg

**Comment by gib** [comment]
This specific case is no longer an issue with the rebrand version.
