### ISSUE TITLE
Switch "Search Our Knowledge Base" on /support to use Swiftype

### ISSUE THREAD

**Issue by fancyremarker** [aptible/www.aptible.com#96]

**Comment by sandersonet** [comment]
@chasballew @fancyremarker What do you guys think about doing the following instead:

* Point www header 'Support' link to support.aptible.com
* Move Support contact form into support.aptible.com, update all 'Contact Us' links on support side to this page
* Remove anything "Knowledge Base" related and instead point to "Getting Started" where necessary
* Move "Legal" into "Company" section of www.

**Comment by fancyremarker** [comment]
I'm fine w/ the first 3 bullet points, defer to @chasballew for the fourth.

**Comment by chasballew** [comment]
1. Yes  
2. Yes  
3. Yes, or support. But get it out of the marketing site.
4. Yes

**Comment by sandersonet** [comment]
Fixed by https://github.com/aptible/www.aptible.com/pull/97
